wifi_hal: fixup compiling
conflict,

device/leeco/x3/libs/wifi_hal/link_layer_stats.cpp:44:11: error: no matching constructor for initialization of 'WifiCommand'
        : WifiCommand(iface, 0), mHandler(handler)